config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

  resources :users ,only:[:index, :show, :edit, :update]
  resources :books ,only:[:index, :create, :show, :update, :edit, :destroy]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20}
  validates :introduction, lingth: {maximum: 50}

  def books
    return Book.where(user_id: self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
  end

  def create
    @books = Book.all
    @book =Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
    else
      render action: :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to book_path(@book)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render action: :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Editing book</h1>

      <%= form_with model:@book, local: true do |f| %>
      <p>Title</p><br>
      <%= f.text_field :title %><br>

      <p>Opinion</p><br>
      <%= f.text_area :body %><br>

      <%= f.submit 'Update Book' %>

      <% end %>

      <%= link_to 'Show', user_path(@book) %>|<%= link_to 'Back', books_path %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">
      <h1>User info</h1>
      <table>
        <tr><%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, fallback: 'no_image.jpg' %></tr>
        <tr>
          <th>name</th>
          <td><%= current_user.name %></td>
        </tr>
        <tr>
          <th>introduction</th>
          <td><%= current_user.introduction %></td>
        </tr>
      </table>

      <div class="edit-profile">
        <%= link_to 'Edit', edit_user_path(current_user) %>
      </div>

      <div class="new-book">
        <h1>New book</h1>
        <%= form_with model:@book, local: true do |f| %>
          <h4>Title</h4><br>
          <%= f.text_field :title %><br>

          <h4>Opinion</h4><br>
          <%= f.text_area :body %><br>

          <%= f.submit 'Create Book' %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table>
        <tr>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: 'no_image.jpeg' %>
            <% end %>
          </td>
          <td><%= link_to "#{book.title}", book_path(book) %></td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">
      <h1>User info</h1>
      <table>
        <tr><%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, fallback: 'no_image.jpg' %></tr>
        <tr>
          <th>name</th>
          <td><%= @book.user.name %></td>
        </tr>
        <tr>
          <th>introduction</th>
          <td><%= @book.user.introduction %></td>
        </tr>
      </table>

      <div class="edit-profile">
        <% if @book.user_id == current_user.id %>
          <%= link_to 'Edit', edit_user_path(@book.user) %>
        <% else %>
          <%= link_to 'Edit', book_path(current_user) %>
        <% end %>
      </div>

      <div class="new-book">
        <h1>New book</h1>
        <%= form_with model:@book_new, local: true do |f| %>
          <h4>Title</h4><br>
          <%= f.text_field :title %><br>

          <h4>Opinion</h4><br>
          <%= f.text_area :body %><br>

          <%= f.submit 'Create Book' %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Books detail</h1>
      <table>
        <tr>
          <td>
            <%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: 'no_image.jpeg' %>
            <% end %>
            </td>
          <td><%= link_to "#{@book.title}", book_path(@book) %></td>
          <td><%= @book.body %></td>
          <% if @book.user_id == current_user.id %>
          <td><%= link_to 'Edit', edit_book_path(@book) %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete %></td>
          <% end %>
        </tr>
      </table>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BOOKERS2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <% if user_signed_in? %>
      <ul>
        <li>
          <%= link_to "Home", user_path(current_user) %>
        </li>
        <li>
          <%= link_to "Users", users_path %>
        </li>
        <li>
          <%= link_to "Books", books_path %>
        </li>
        <li>
          <%= link_to "logout", destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    <% else %>
      <ul>
        <li>
          <%= link_to 'HOME', root_path %>
        </li>
        <li>
          <%= link_to 'About', root_path %>
        </li>
        <li>
          <%= link_to 'sign up', new_user_registration_path %>
        </li>
        <li>
          <%= link_to 'login', new_user_session_path %>
        </li>
      </ul>
    <% end %>
    </header>

    <%= yield %>

    <footer><h2>CopyRight Infratop.inc</h2></footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>User info</h1>

      <%= form_with model:@user, local: true do |f| %>
      <p>Name</p><br>
      <%= f.text_field :name %><br>

      <p>Image</p><br>
      <%= f.attachment_field :profile_image %><br>

      <p>Introduction</p><br>
      <%= f.text_area :introduction %><br>

      <%= f.submit 'Update User' %>

      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">
      <h1>User info</h1>
      <table>
        <tr><%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, fallback: 'no_image.jpg' %></tr>
        <tr>
          <th>name</th>
          <td><%= current_user.name %></td>
        </tr>
        <tr>
          <th>introduction</th>
          <td><%= current_user.introduction %></td>
        </tr>
      </table>

      <div class="edit-profile">
        <%= link_to 'Edit', edit_user_path(current_user) %>
      </div>

      <div class="new-book">
        <h1>New book</h1>
        <%= form_with model:@book, local: true do |f| %>
          <h4>Title</h4><br>
          <%= f.text_field :title %><br>

          <h4>Opinion</h4><br>
          <%= f.text_area :body %><br>

          <%= f.submit 'Create Book' %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Users</h1>
      <table>
        <tr>
          <th>image</th>
          <th>name</th>
        </tr>
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user,:profile_image, :fill, 60, 60, fallback: "no_image.jpeg" %></td>
          <td><%= user.name %></td>
          <td><%= link_to 'Show', user_path(user) %></td>
        </tr>
        <% end %>
      </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">
      <h1>User info</h1>
      <table>
        <tr><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: 'no_image.jpg' %></tr>
        <tr>
          <th>name</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>introduction</th>
          <td><%= @user.introduction %></td>
        </tr>
      </table>

      <div class="edit-profile">
        <% if @user.id == current_user.id %>
          <%= link_to 'Edit', edit_user_path(current_user) %>
        <% else %>
          <%= link_to 'Edit', user_path(current_user) %>
        <% end %>
      </div>

      <div class="new-book">
        <h1>New book</h1>
        <%= form_with model:@book, local: true do |f| %>
          <h4>Title</h4><br>
          <%= f.text_field :title %><br>

          <h4>Opinion</h4><br>
          <%= f.text_area :body %><br>

          <%= f.submit 'Create Book' %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table>
        <tr>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        <% @user.books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: 'no_image.jpg' %>
            <% end %>
          </td>
          <td><%= link_to "#{book.title}", book_path(book) %></td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </table>
    </div>

  </div>
</div>